spring.application.name=secure-banking-system

# Railway MySQL
spring.datasource.url=jdbc:mysql://root:YgLsfRFJZkuitGmoNsHVaBRJuEZMlrBY@sakura.proxy.rlwy.net:31351/railway
spring.datasource.username=root
spring.datasource.password=YgLsfRFJZkuitGmoNsHVaBRJuEZMlrBY
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080